# Default values for secretify.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  # provide a secret with an ingrid registry dockerconfigjson https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  # kubectl create secret docker-registry ingrid-registry --docker-server=<your-registry-server> --docker-username=<your-name> --docker-password=<your-pword>
  registryConfig: ""
  # if no registry secret provided, define the ingrid registry data here. The secret will be used by the serviceAccount and allows re-use for any additional ingrid services
  registry: ""
  username: ""
  password: ""
  email: ""
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest
  pullPolicy: Always


core:
  enabled: true
  registry:
    image: dariocalovic/secretify
    tag: 0.2.3-beta
  ingress:
    enabled: true
    host: secretify.kubernetes
    path:
      api: /api
      ui: /
  resources:
    requests:
      memory: 16Mi
      cpu: 20m
    limits:
      memory: 32Mi
      cpu: 200m













imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
